### ISSUE TITLE
Make Shuttle action point to point at multiple scripts

### ISSUE THREAD

**Issue by sofusalbertsen** [lunarway/shuttle#138]
As a user, I would like to architect my scripts in smaller chunks, but be able to call them all with a "super target", so that I can make only one call to shuttle.
Example (written in make syntax)

```
# Super target for destroying infra. 
.PHONY: all-destroy
all-destroy: vacuum-cluster \
             cluster-rm \
             networking-rm \
             vpc-rm \

```

**Comment by Crevil** [comment]
I guess you can just call shuttle in a script like

```yaml
scripts:
  all-destroy:
    description: Destroy all the things
    actions:
    - shell: shuttle run vacuum-cluster
    - shell: shuttle run cluster-rm
    - shell: shuttle run networking-rm
    - shell: shuttle run vpc-rm
```

It is a bit verbose ofc, but might work?

An alternative could be to add a `shuttle` script exector so something like this would be possible:

```yaml
scripts:
  all-destroy:
    description: Destroy all the things
    actions:
    - shuttle: vacuum-cluster
    - shuttle: cluster-rm
    - shuttle: networking-rm
    - shuttle: vpc-rm
```

Not a whole lot better I think. WDYT?

**Comment by sofusalbertsen** [comment]
Thanks @Crevil for replying.
I get that the shuttlescript won't really give you that much more in terms of readability.
But if you made it into an internal script action, then all env and flags you sent to shuttle would be the same in the child commands you detail in your action.

So in the original make script, I would like to be able to execute all the sub-targets regardless if one of them fails or not (imagine that part of my install script worked, and now I want to clean up).

Then I would need a `--keep-going` equivalent, that I then would love to trickle down to my child commands as well.

Does that make sense in your way of envisioning shuttle usage?

**Comment by Crevil** [comment]
With the current `shell` action that would already work I think.

```yaml
# shuttle.yaml
plan: false
scripts:
  cluster-rm:
    actions:
      - shell: echo "Removing cluster from $hello"
  all-destroy:
    args:
      - name: hello
    actions:
      - shell: shuttle run cluster-rm
```

When running `all-destroy` it can reference `hello`.

```
$ shuttle run all-destroy hello=world
Removing cluster from world
```

Is this what you want?
