### ISSUE TITLE
Validation of script arguments

### ISSUE THREAD

**Issue by Crevil** [lunarway/shuttle#15]
If would be great if arguments for scripts were validated before issuing the command.

It would require some syntax for writing requirements of an argument in a plan. This could very well be the same syntax required for #6 for validating the plan schema.

This could add more descriptive help messages as well (#14) as we define what values are allowed up front.

### Example

A naive implementation would be something like below with key `validation` on the argument.
```yaml
plan: git://git@bitbucket.org:LunarWay/lw-shuttle-go-plan.git
scripts:
  my_script:
    description: a description
    args:
    - name: foo
      required: true
      validation:
        - someValue
        - someOtherValue
    actions:
    - shell: './run.sh'
```

```
$ shuttle run my_script foo=someWrongValue
Argument foo contains an invalid value "someWrongValue". Allowed values: "someValue", "someOtherValue"
```
