### ISSUE TITLE
Shell output with percentage signs are wrongly encoded

### ISSUE THREAD

**Issue by Crevil** [lunarway/shuttle#18]
Any scripts that output a percentage sign is wrongly outputtet as it is recognised as a placeholder.

With the following `shuttle.yaml`

```yaml
plan: false
scripts:
  percentage:
    actions:
    - shell: echo '%'
```

Running `shuttle run percentage` outputs

```
$ shuttle run percentage
shell: echo '%'
%!(NOVERB)
```

I expected it to output the following instead.

```
$ shuttle run percentage
shell: echo '%'
%
```

**Comment by Crevil** [comment]
The same happens for Stderr output in shells

```yaml
plan: false
scripts:
  percentage:
    actions:
    - shell: ">&2 echo '%'"
```

outputs

```
$ shuttle run percentage
shell: >&2 echo '%'
%!ISSING)[0m
```
