### ISSUE TITLE
Fail on unknown arguments

### ISSUE THREAD

**Issue by Crevil** [lunarway/shuttle#38]
If one runs a script with arguments that are not specified for the script it is silently ignored.
This makes it error prone for non-required fields.

```yaml
scripts:
  test:
    args:
      - name: version
    actions:
      - shell: echo "Version $version"
```

```
$ shuttle run test versoin=123
Version
$ echo $?
0
```

I would expect the above command to at least exit with a non-zero status.
Preferable with a message like `unknown argument "versoin"`
